# Generated by Django 4.0 on 2022-08-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_alter_set_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='set',
            name='user',
        ),
    ]
