# Generated by Django 4.0 on 2022-08-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='learning.card'),
        ),
    ]
